#!/bin/bash
ldc2 -O5 -partially-inline-libcalls -singleobj -release -output-ll ./vxwclient-voxlap-renderer/*.d ./vxwclient-voxlap-renderer/*.di *.d *.di ./derelict/sdl2/*.d ./derelict/enet/*.d ./derelict/util/*.d -ofmain.ll
echo 20% done
llvm-link  main.ll ./vxwclient-voxlap-renderer/kplib.ll ./vxwclient-voxlap-renderer/voxlap5.ll -S -o client.ll
echo 40% done
opt -O3 -inline-threshold=1000 -mcpu=penryn client.ll -S -o client_opt.ll
echo 60% done
llc -O3 -inline-threshold=100000 -mcpu=penryn client_opt.ll -filetype=obj -o main.o
echo 80% done
gcc -pg -Ofast main.o -o main -lslang -lphobos2-ldc -Wl,-Ofast -ldruntime-ldc -ldl -lpthread -lm -march=native